version: "3.8"
services:
  literature-review:
    build: ./webservice
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webservice/src/main/litreviewapi:/opt/literaturereview
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - redis
      - kafka
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=litreview
      - POSTGRES_PASSWORD=litreview
      - POSTGRES_DB=litreview
  redis:
    image: redis:6.2.6 # port 6379
    ports:
      - "6379:6379"
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
volumes:
  postgres_data:
